apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: 200915316788.dkr.ecr.us-east-1.amazonaws.com/frontend

---
apiVersion: v1
kind: Pod
metadata:
  name: auth-service
spec:
  containers:
    - name: auth-service
      image: 200915316788.dkr.ecr.us-east-1.amazonaws.com/auth-service
      env:
        - name: DB_HOST
          value: {{ aws_rds_endpoint_address }}
        - name: DEMO_FAREWELL
          value: "Such a sweet sorrow"
          Environment=DB_HOST={{ aws_rds_endpoint_address }}
          Environment=DB_PORT=5432
          Environment=DB_USER=auth_svc_user
          Environment=DB_PASSWORD=localdev123
          Environment=DB_NAME=wmp
          Environment=DB_SCHEMA=auth_schema
          Environment=SERVER_PORT=8081
          Environment=JWT_SECRET=myDefaultSuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm
          Environment=PORTFOLIO_SERVICE_URL=http://portfolio-service-dev.devopsbymanju.shop:8080

---
apiVersion: v1
kind: Pod
metadata:
  name: portfolio-service
spec:
  containers:
    - name: portfolio-service
      image: 200915316788.dkr.ecr.us-east-1.amazonaws.com/portfolio-service

---

apiVersion: v1
kind: Pod
metadata:
  name: analytics-service
spec:
  containers:
    - name: analytics-service
      image: 200915316788.dkr.ecr.us-east-1.amazonaws.com/analytics-service