apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
    - name: frontend
      image: 200915316788.dkr.ecr.us-east-1.amazonaws.com/frontend

---
apiVersion: v1
kind: Pod
metadata:
  name: auth-service
spec:
  containers:
    - name: auth-service
      image: 200915316788.dkr.ecr.us-east-1.amazonaws.com/auth-service
      env:
        - name: DB_HOST
          value: {{ aws_rds_endpoint_address }}
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: auth_svc_user
        - name: DB_PASSWORD
          value: localdev123
        - name: DB_NAME
          value: wmp
        - name: DB_SCHEMA
          value: auth_schema
        - name: SERVER_PORT
          value: "8081"
        - name: JWT_SECRET
          value: myDefaultSuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm
        - name: PORTFOLIO_SERVICE_URL
          value: http://portfolio-service-dev.devopsbymanju.shop:8080


---
apiVersion: v1
kind: Pod
metadata:
  name: portfolio-service
spec:
  containers:
    - name: portfolio-service
      image: 200915316788.dkr.ecr.us-east-1.amazonaws.com/portfolio-service

---

apiVersion: v1
kind: Pod
metadata:
  name: analytics-service
spec:
  containers:
    - name: analytics-service
      image: 200915316788.dkr.ecr.us-east-1.amazonaws.com/analytics-service